//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlindDriver.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlindDriver.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aweful!.
        /// </summary>
        internal static string awful {
            get {
                return ResourceManager.GetString("awful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad!.
        /// </summary>
        internal static string bad {
            get {
                return ResourceManager.GetString("bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best time:.
        /// </summary>
        internal static string best_time {
            get {
                return ResourceManager.GetString("best_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind Driver.
        /// </summary>
        internal static string blind_driver {
            get {
                return ResourceManager.GetString("blind_driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe right and left to change the race..
        /// </summary>
        internal static string choose_race_read {
            get {
                return ResourceManager.GetString("choose_race_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown starts now..
        /// </summary>
        internal static string countdown {
            get {
                return ResourceManager.GetString("countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string decent {
            get {
                return ResourceManager.GetString("decent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty:.
        /// </summary>
        internal static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string easy {
            get {
                return ResourceManager.GetString("easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish!.
        /// </summary>
        internal static string end {
            get {
                return ResourceManager.GetString("end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excelent!.
        /// </summary>
        internal static string excelent {
            get {
                return ResourceManager.GetString("excelent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        internal static string extreme {
            get {
                return ResourceManager.GetString("extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear: {0}           Speed:  {1} kmph.
        /// </summary>
        internal static string GearAndSpeed {
            get {
                return ResourceManager.GetString("GearAndSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good!.
        /// </summary>
        internal static string good {
            get {
                return ResourceManager.GetString("good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        internal static string hard {
            get {
                return ResourceManager.GetString("hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        internal static string instruction {
            get {
                return ResourceManager.GetString("instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface instructions:
        ///To go back to the previous screen: tap the screen two times. During the game tap once to pause the game and tap twice to end the race.
        ///Game instructions:
        ///The Blind Driver is a game that simulates a WCR racing. The player has to finish a race track as fast as possible. To accelerate tilt the device forward. To make a turn - turn the device left or right as a steering wheel. During the race the pilot will be instructing the player of every turn with it&apos;s severity. And so a &quot;Right on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string instructionContent {
            get {
                return ResourceManager.GetString("instructionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello. Click left half of the screen to go to instructions or right side of the screen to choose the race..
        /// </summary>
        internal static string introduction_read {
            get {
                return ResourceManager.GetString("introduction_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left one.
        /// </summary>
        internal static string l1 {
            get {
                return ResourceManager.GetString("l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left two.
        /// </summary>
        internal static string l2 {
            get {
                return ResourceManager.GetString("l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left three.
        /// </summary>
        internal static string l3 {
            get {
                return ResourceManager.GetString("l3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left four.
        /// </summary>
        internal static string l4 {
            get {
                return ResourceManager.GetString("l4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left five.
        /// </summary>
        internal static string l5 {
            get {
                return ResourceManager.GetString("l5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track length:.
        /// </summary>
        internal static string length {
            get {
                return ResourceManager.GetString("length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meters..
        /// </summary>
        internal static string meters {
            get {
                return ResourceManager.GetString("meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the new record!.
        /// </summary>
        internal static string new_record {
            get {
                return ResourceManager.GetString("new_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set.
        /// </summary>
        internal static string not_set {
            get {
                return ResourceManager.GetString("not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        internal static string one {
            get {
                return ResourceManager.GetString("one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right one.
        /// </summary>
        internal static string r1 {
            get {
                return ResourceManager.GetString("r1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right two.
        /// </summary>
        internal static string r2 {
            get {
                return ResourceManager.GetString("r2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right three.
        /// </summary>
        internal static string r3 {
            get {
                return ResourceManager.GetString("r3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right four.
        /// </summary>
        internal static string r4 {
            get {
                return ResourceManager.GetString("r4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right five.
        /// </summary>
        internal static string r5 {
            get {
                return ResourceManager.GetString("r5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string race {
            get {
                return ResourceManager.GetString("race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You chose a race.
        /// </summary>
        internal static string race_chosen {
            get {
                return ResourceManager.GetString("race_chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race {0}. Difficulty {1}. Length {2} meters. Best time {3}.
        /// </summary>
        internal static string RaceChooseDetails {
            get {
                return ResourceManager.GetString("RaceChooseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume race.
        /// </summary>
        internal static string resume {
            get {
                return ResourceManager.GetString("resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds..
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go!.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        internal static string three {
            get {
                return ResourceManager.GetString("three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        internal static string two {
            get {
                return ResourceManager.GetString("two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your time is.
        /// </summary>
        internal static string your_time {
            get {
                return ResourceManager.GetString("your_time", resourceCulture);
            }
        }
    }
}
